### PR TITLE
feat: Window expansion on Initialization

### LINKED ISSUE #55: window expansion when initialised
hey, would it be possible that the window expands to its fullest when initialised to show all the params possible before scrolling takes over? Otherwise you always have to manually expand the window.

see the example below:

(
Ndef(\test, {
	var freqRange = \freqRange.kr(Array.fill(20, {440}), spec: ControlSpec(20, 1000));
}).gui2;
)

### PR DESCRIPTION
**Pull request by salkin-mada**
fix #55

### CODE REVIEW

**Comment by salkin-mada** [comment]
Caveat found:
Depending on the display size -> `Window.availableBounds` there is a threshold which is off. Because we are not including the title-bar height in the calculation. I guess.. Juust before scrolling is really needed, the condition is triggered and the window is being set to "max height". But there is actually space left. The result is that the value boxes are not being padded neatly vertically in the **VLayout**. Everything else is made a bit higher..
Visual explanation:
Screenshot 2024-10-24 at 01 22 14

**Comment by redFrik** [comment]
thanks.  tested in SCIDE and seems to work great.
although i feel there's a simpler way that also would avoid that additional resize (window.view.bounds_).  make me a bit nervous.

**Comment by salkin-mada** [comment]
I completely agree. Let me know if you have any thoughts on _how_. You can also just amend the PR.

**Comment by salkin-mada** [comment]
done proper in #57 , closing

**Pull request closed without merging**
