### PR TITLE
add excludeParams

### PR DESCRIPTION
**Pull request by redFrik**
as proposed by dietcv

### CODE REVIEW

**Comment by dietcv** [comment]
great. ive tested your implementation. it seems the first time i evaluate the following code it does nothing at all. the second time i evaluate it with the first gui still open \amp is excluded as i would expect:

(
Ndef(\test, {
var freqRange = \freq.kr(100, spec: ControlSpec(20, 1000));
var ampRange = \amp.kr(0.5, spec: ControlSpec(0, 1));
}).gui2.excludeParams_([\amp]);
)

**Comment by redFrik** [comment]
correct and (unfortunately) the expected result.
you're creating the NodeProxyGui2 instance and _then_ setting which parameters to exclude.  so the gui is already setup and created before you tell it which params to exclude.

not optimal i know but here are two ways around it....
```
(
Ndef(\test, {
	var freq = \freq.kr(100, spec: ControlSpec(20, 1000));
	var amp = \amp.kr(0.5, spec: ControlSpec(0, 1));
}).gui2.excludeParams_([\amp]);
{
	Ndef(\test).rebuild;
}.defer
)

(
NodeProxyGui2.defaultExcludeParams_([\amp]);
Ndef(\test, {
	var freq = \freq.kr(100, spec: ControlSpec(20, 1000));
	var amp = \amp.kr(0.5, spec: ControlSpec(0, 1));
}).gui2;
)
```

**Comment by redFrik** [comment]
but wait!
your question and example made me think of a solution to the problem. and of course it should work like you describe.
i've updated this PR with a fix. please try again. thanks.

**Comment by dietcv** [comment]
thanks for clarifying. your latest change does work for me. 
I had a bunch of arrays with buffers and some arrays for demand sequences which are better controlled by using .set imo.
so much more window space now. thanks alot.

**Comment by redFrik** [comment]
great. we'll commit this soon.
thanks for the suggestion and for testing.

**Comment by dietcv** [comment]
i think i found and additional issues:

if you exclude parameters from the gui using .excludeParams_( ), create a document by using the drop down menu (all params included here) and use .set to update the NodeProxy with the params of your document, the sliders wont update. only if you use a selection of parameters without the excluded ones.

**Comment by redFrik** [comment]
wow! impressive that you found this bug. must've been hiding there in the original version too, but this addition triggered it to crawl out.
now squashed.

**Comment by dietcv** [comment]
great :)

**Pull request merged**
